

Import required libraries


In [2]:
import os
from sklearn.tree import DecisionTreeClassifier, export_graphviz
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from time import time
from sklearn import preprocessing
from sklearn.pipeline import Pipeline
from sklearn.metrics import roc_auc_score , classification_report
from sklearn.metrics import precision_score, recall_score, accuracy_score, classification_report

Read dataset of car evaluation

In [4]:
dataset = pd.read_csv("tic-tac-toe.csv")
dataset.head()

id 'top-left-square' 'top-middle-square' 'top-right-square'  \
0   1                 x                   x                  x   
1   2                 x                   x                  x   
2   3                 x                   x                  x   
3   4                 x                   x                  x   
4   5                 x                   x                  x   

  'middle-left-square' 'middle-middle-square' 'middle-right-square'  \
0                    x                      o                     o   
1                    x                      o                     o   
2                    x                      o                     o   
3                    x                      o                     o   
4                    x                      o                     o   

  'bottom-left-square' 'bottom-middle-square' 'bottom-right-square'   'Class'  
0                    x                      o                     o  positive  
1                    o                      x                     o  positive  
2                    o                      o                     x  positive  
3                    o                      b                     b  positive  
4                    b                      o                     b  positive

Encode categorical values of target variable to numerical

In [10]:
from sklearn.preprocessing import LabelEncoder

labelEncoder = LabelEncoder()
print(dataset.columns)
dataset['\'Class\''] = labelEncoder.fit_transform(dataset['\'Class\''])
dataset['\'Class\''].unique()

Index(['id', ''top-left-square'', ''top-middle-square'', ''top-right-square'',
       ''middle-left-square'', ''middle-middle-square'',
       ''middle-right-square'', ''bottom-left-square'',
       ''bottom-middle-square'', ''bottom-right-square'', ''Class''],
      dtype='object')


array([1, 0])

In [15]:
le = preprocessing.LabelEncoder()
for col in dataset.columns:
    dataset[col] = le.fit_transform(dataset[col])

get features and target variables

In [17]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values
print("Shape of x: ", X.shape)
print("Shape of y: ", y.shape)

Shape of x:  (958, 10)
Shape of y:  (958,)


split into train and test data

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print("Shape of x_train: ", X_train.shape)
print("Shape of y_train: ", y_train.shape)
print("shape of x_test: ", X_test.shape)
print("shape of y_test: ", y_test.shape)


Shape of x_train:  (191, 10)
Shape of y_train:  (191,)
shape of x_test:  (767, 10)
shape of y_test:  (767,)


Perform feature scaling with standardisation

Descision tree classifier with default depth

In [36]:
t0=time()
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

# creating a model
model = DecisionTreeClassifier()
# feeding the training data into the model
model.fit(X_train, y_train)

# predicting the values for x-test
y_pred = model.predict(X_test)

# finding the training and testing accuracy
print("Training Accuracy: ",model.score(X_train, y_train))
print("Testing Accuracy: ", model.score(X_test, y_test))

# printing the confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
micro_precision = precision_score(y_pred, y_test, average='micro')
print('Micro-averaged precision score: {0:0.2f}'.format(
      micro_precision))

t1=time()
print ("time elapsed: ", t1-t0)

Training Accuracy:  1.0
Testing Accuracy:  1.0
[[270   0]
 [  0 497]]
Micro-averaged precision score: 1.00
time elapsed:  0.009250879287719727


Decision tree with depth 3

In [37]:
t0=time()
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

# creating a model
model = DecisionTreeClassifier(max_depth = 3)
# feeding the training data into the model
model.fit(X_train, y_train)

# predicting the values for x-test
y_pred = model.predict(X_test)

# finding the training and testing accuracy
print("Training Accuracy: ",model.score(X_train, y_train))
print("Testing Accuracy: ", model.score(X_test, y_test))

# printing the confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

micro_precision = precision_score(y_pred, y_test, average='micro')
print('Micro-averaged precision score: {0:0.2f}'.format(
      micro_precision))
t1=time()
print ("time elapsed: ", t1-t0)

Training Accuracy:  1.0
Testing Accuracy:  1.0
[[270   0]
 [  0 497]]
Micro-averaged precision score: 1.00
time elapsed:  0.008149862289428711


 plotting the graph for performance of decision trees with different max_depth values

In [22]:
tt0=time()
print ("cross result========")
scores = cross_val_score(model, X, y, cv=3)
print (scores)
print (scores.mean())
tt1=time()
print ("time elapsed: ", tt1-tt0)

cross result========
[0.825      1.         0.67398119]
0.8329937304075234
time elapsed:  0.013637542724609375
